### ISSUE TITLE
#4 - External links to informative wikis of each god

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/mp1-legends-of-asgard#3]
I am a Norse Mythology student, and within each section I would like to click a link that goes to external knowledge articles with more in depth information, so that I can build on my knowledge and ensure my work is cited from   

## Acceptance Criteria

- [ ]  This site alone wont be able to hold every piece of information so there should be external links for each god or saga to credible external information opening in new tab

## Tasks

- [ ]  Add a ‘see more’ or ‘get more info’ link to each section of important info that opens to an external wiki
- [ ]  Make the all external links open in new tab and ensure they don’t link back to this site for security
