### ISSUE TITLE
#5 - Social links and sharing

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/mp1-legends-of-asgard#4]
I am a Norse Mythology teacher, and I would like the ability to share information about the Viking gods and Sagas, so that I can easily share them with my students in an interesting format

## Acceptance Criteria

- [x]  The header section should contain social links either in the navbar or the header
- [x]  Each section must have a link to share that particular section of information

## Tasks

- [x]  Add social link icons into header and footer sections with link to social accounts
- [x]  Add a share icon linking to functionality to share with someone

**Comment by Dave-MK** [comment]
Slight change to this, social links are fixed and are accessible no matter where the user is on the page.

Also no need for share button as this is available through most browsers.
