### ISSUE TITLE
#7 - Ability to contact the site owner

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/mp1-legends-of-asgard#6]
I am a event planner, and I would like to contact the site owner, to discuss working together on a Norse themed event I am planning

## Acceptance Criteria

- [x]  A contact form in the footer section
- [x]  A link in the header to the contact section on each page

## Tasks

- [x]  Add a bootstrap contact form in the footer with required fields: name, email, message and submit button
- [x]  Style form with custom css
- [x]  Ensure form is responsive on all major devices
