### ISSUE TITLE
#1 - Easy navigation

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/mp1-legends-of-asgard#8]
I am a Mythology/Folklore enthusiast, I would like an area showing all the gods with links to their short blurbs and saga info displayed in eye catching card format, so that I may quickly find the sagas and all the information I need

## Acceptance Criteria

- [x]  A one page structure containing several sections with information and images structured with HTML and Bootstrap and custom styled with CSS
- [x]  The top section of the page must contain the title of the site and short description, navigation to important areas and a picture of each god that links to their section of information, possibly fixed to the bottom of the screen

## Tasks

- [x]  Create boilerplate HTML structure, with meta description and keywords and containing sections: header, main and footer
- [x]  Link Bootstrap css and js cdn, fontawesome kit and custom css file
- [x]  Create a nav inside the header and at least 7 sections within the main area with id’s of: #odin, #thor, #loki, #freya, #tyr #hel and #sif

**Comment by Dave-MK** [comment]
Slight change made to minimise complication, which was removing bootstrap and doing all styling myself.

**Comment by Dave-MK** [comment]
Changed menu from bottom of screen to right of screen
