### ISSUE TITLE
#2 - Simple but effective flow of desired information

### ISSUE THREAD

**Issue by Dave-MK** [Dave-MK/mp1-legends-of-asgard#9]
I am a Mythology/Folklore enthusiast, I would like an area showing all the gods with links to their short blurbs and saga info displayed in eye catching card format, so that I may quickly find the sagas and all the information I need

## Acceptance Criteria
- [x]  Each section must be full width and height of the viewport and should snap when scrolled with images and information about the God and a Saga relating to them
- [x]  Each god section should display the information in carousel form to allow for readability and information overflow
- [x]  The site should be fully responsive on all major device widths

## Tasks
- [x]  Add navigation, title and description and standalone images of each God in a carousel like format, linking to their respective section with a background image of some epic scenery (carousel to be fixed to bottom of page)
- [x]  Add carousel functionality to the header for each relating to the relevant God and add classes to make site full width and height
- [x]  Add css scroll snapping and add bootstrap and media queries for responsiveness

**Comment by Dave-MK** [comment]
Carousel functionality is just now related to the menu using CSS and bootstrap is no longer being used
